struct FilterVar /Abstract/ {
%TypeHeaderCode
#include <pyfc/pyfilter.h>
%End
};

struct Filter1d : FilterVar /Abstract/ {
%TypeHeaderCode
#include <pyfc/pyfilter.h>
%End
};

struct Filter2d : FilterVar /Abstract/ {
%TypeHeaderCode
#include <pyfc/pyfilter.h>
%End
};

struct Filter3d : FilterVar /Abstract/ {
%TypeHeaderCode
#include <pyfc/pyfilter.h>
%End
};

struct Filter4d : FilterVar /Abstract/ {
%TypeHeaderCode
#include <pyfc/pyfilter.h>
%End
};
